# Generated by Django 2.0.3 on 2018-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_src',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
