# Generated by Django 2.0.3 on 2018-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='certifying_authority',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
